server:
  port: 8081
  tomcat:
    basedir: /tmp/tomcat
spring:
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
